import 'dart:convert';
import 'dart:typed_data';

import 'package:dpdf/dpdf.dart';
import 'package:test/test.dart';

/// Reproductions of what the producers of real documents actually write.
///
/// Every fixture here is assembled in the test itself, from the shapes seen in
/// municipal gazettes generated by Adobe InDesign/Distiller: a ToUnicode CMap
/// that declares the two-byte Identity codespace for a single-byte font, a
/// `gs` on every page for transparency alone, `BX`/`EX` brackets, an embedded
/// subset with a named encoding and no ToUnicode, and a subset Identity font
/// whose program no longer carries a `cmap` table.

Future<Uint8List> _document(String content, PdfDictionary resources) async {
  final output = BytesBuilder(copy: false);
  final document = PdfDocument.create(PdfWriter.fromBytesBuilder(output));
  final page = await document.appendBlankPage();
  page.pdfRepresentation().put(PdfName.resources, resources);
  page.pdfRepresentation().put(PdfName.contents,
      PdfStream.withBytes(Uint8List.fromList(latin1.encode(content)), 0));
  await document.close();
  return output.takeBytes();
}

Future<String> _textOf(Uint8List bytes) async {
  final document = await PdfDocument.open(PdfReader.fromBytes(bytes));
  try {
    return await PdfTextExtraction.fromPage((await document.pageAt(1))!);
  } finally {
    await document.close();
  }
}

Future<String> _extract(String content, PdfDictionary resources) async =>
    _textOf(await _document(content, resources));

PdfStream _cmap(String body) => PdfStream.withBytes(
    Uint8List.fromList(ascii.encode('/CIDInit /ProcSet findresource begin\n'
        '12 dict begin\nbegincmap\n'
        '/CMapName /Adobe-Identity-UCS def\n/CMapType 2 def\n'
        '1 begincodespacerange\n<0000> <FFFF>\nendcodespacerange\n'
        '$body\n'
        'endcmap CMapName currentdict /CMap defineresource pop end end')),
    0);

/// A simple font as the corpus writes it: TrueType, optional named encoding,
/// optional ToUnicode whose codespace is the Identity default.
PdfDictionary _simpleFont(
    {String? encoding, PdfStream? toUnicode, int? flags}) {
  final font = PdfDictionary()
    ..put(PdfName.type, PdfName.font)
    ..put(PdfName.subtype, PdfName('TrueType'))
    ..put(PdfName.baseFont, PdfName('ABCDEF+Test'));
  if (encoding != null) font.put(PdfName.encoding, PdfName(encoding));
  if (toUnicode != null) font.put(PdfName('ToUnicode'), toUnicode);
  if (flags != null) {
    font.put(
        PdfName('FontDescriptor'),
        PdfDictionary()
          ..put(PdfName.type, PdfName('FontDescriptor'))
          ..put(PdfName('FontName'), PdfName('ABCDEF+Test'))
          ..put(PdfName('Flags'), PdfNumber.fromInt(flags)));
  }
  return font;
}

PdfDictionary _fontResources(PdfDictionary font) => PdfDictionary()
  ..put(PdfName.font, PdfDictionary()..put(PdfName('F1'), font));

/// An sfnt table directory listing [tables] and nothing else. The bytes past
/// the directory are never read: a program with no `cmap` is rejected before
/// any table is parsed, which is exactly what this stands in for.
PdfStream _sfntStub(List<String> tables) {
  final bytes = BytesBuilder();
  final header = ByteData(12)
    ..setUint32(0, 0x00010000)
    ..setUint16(4, tables.length);
  bytes.add(header.buffer.asUint8List());
  for (final tag in tables) {
    final record = ByteData(16)
      ..setUint32(4, 0)
      ..setUint32(8, 12 + tables.length * 16)
      ..setUint32(12, 0);
    bytes.add(Uint8List.fromList(ascii.encode(tag)));
    bytes.add(record.buffer.asUint8List().sublist(4));
  }
  bytes.add(Uint8List(4));
  return PdfStream.withBytes(bytes.takeBytes(), 0);
}

/// Identity-H over a CIDFontType2 subset, the composite shape of the corpus.
PdfDictionary _identityFont(
    {required PdfStream program, String ordering = 'Identity'}) {
  final descriptor = PdfDictionary()
    ..put(PdfName.type, PdfName('FontDescriptor'))
    ..put(PdfName('FontName'), PdfName('ABCDEF+Test'))
    ..put(PdfName('Flags'), PdfNumber.fromInt(4))
    ..put(PdfName('FontFile2'), program);
  final descendant = PdfDictionary()
    ..put(PdfName.type, PdfName.font)
    ..put(PdfName.subtype, PdfName('CIDFontType2'))
    ..put(PdfName.baseFont, PdfName('ABCDEF+Test'))
    ..put(PdfName('CIDToGIDMap'), PdfName('Identity'))
    ..put(PdfName('FontDescriptor'), descriptor)
    ..put(
        PdfName('CIDSystemInfo'),
        PdfDictionary()
          ..put(PdfName('Registry'), PdfString('Adobe'))
          ..put(PdfName('Ordering'), PdfString(ordering))
          ..put(PdfName('Supplement'), PdfNumber.fromInt(0)));
  return PdfDictionary()
    ..put(PdfName.type, PdfName.font)
    ..put(PdfName.subtype, PdfName('Type0'))
    ..put(PdfName.baseFont, PdfName('ABCDEF+Test'))
    ..put(PdfName.encoding, PdfName('Identity-H'))
    ..put(PdfName('DescendantFonts'), PdfArray.fromList([descendant]));
}

void main() {
  group('ExtGState', () {
    test('a graphics state without /Font cannot move text and is stepped over',
        () async {
      final resources =
          _fontResources(_simpleFont(encoding: 'WinAnsiEncoding', flags: 32))
            ..put(
                PdfName('ExtGState'),
                PdfDictionary()
                  ..put(
                      PdfName('GS0'),
                      PdfDictionary()
                        ..put(PdfName.type, PdfName('ExtGState'))
                        ..put(PdfName('BM'), PdfName('Normal'))
                        ..put(PdfName('CA'), PdfNumber(1))
                        ..put(PdfName('ca'), PdfNumber(1))
                        ..put(PdfName('SMask'), PdfName('None'))));
      expect(
          await _extract(
              'q /GS0 gs BT /F1 12 Tf (Rio das Ostras) Tj ET Q\n', resources),
          'Rio das Ostras');
    });

    test('a graphics state carrying /Font is refused, and says so', () async {
      final font = _simpleFont(encoding: 'WinAnsiEncoding', flags: 32);
      final resources = _fontResources(font)
        ..put(
            PdfName('ExtGState'),
            PdfDictionary()
              ..put(
                  PdfName('GS0'),
                  PdfDictionary()
                    ..put(PdfName.type, PdfName('ExtGState'))
                    ..put(PdfName.font,
                        PdfArray.fromList([font, PdfNumber.fromInt(12)]))));
      await expectLater(
          _extract('q /GS0 gs BT /F1 12 Tf (A) Tj ET Q\n', resources),
          throwsA(isA<UnsupportedError>().having((e) => '${e.message}',
              'message', allOf(contains('gs /GS0'), contains('/Font')))));
    });

    test('a gs naming no resource is a malformed stream, not an unknown one',
        () async {
      await expectLater(
          _extract('q /GS0 gs BT /F1 12 Tf (A) Tj ET Q\n',
              _fontResources(_simpleFont(encoding: 'WinAnsiEncoding'))),
          throwsA(isA<FormatException>().having((e) => e.message, 'message',
              contains('Missing /ExtGState entry /GS0'))));
    });
  });

  group('marked-content points', () {
    test('DP marks a point with no content and is stepped over', () async {
      final resources =
          _fontResources(_simpleFont(encoding: 'WinAnsiEncoding', flags: 32))
            ..put(
                PdfName('Properties'),
                PdfDictionary()
                  ..put(
                      PdfName('MC0'),
                      PdfDictionary()
                        ..put(PdfName('MCID'), PdfNumber.fromInt(0))));
      expect(
          await _extract(
              '/Span /MC0 DP BT /F1 12 Tf (Atos) Tj ET /Span <</MCID 1>> DP\n',
              resources),
          'Atos');
    });

    test('DP carrying /ActualText is refused instead of dropped', () async {
      await expectLater(
          _extract(
              'BT /F1 12 Tf (A) Tj ET /Span <</ActualText (Z)>> DP\n',
              _fontResources(
                  _simpleFont(encoding: 'WinAnsiEncoding', flags: 32))),
          throwsA(isA<UnsupportedError>().having((e) => '${e.message}',
              'message', allOf(contains('ActualText'), contains('DP')))));
    });
  });

  group('ToUnicode written against the Identity codespace', () {
    test('single-byte codes decode under a two-byte declared codespace',
        () async {
      final font = _simpleFont(
          toUnicode: _cmap('2 beginbfchar\n<41> <0041>\n<42> <0042>\n'
              'endbfchar'));
      expect(
          await _extract('BT /F1 12 Tf <4142> Tj ET\n', _fontResources(font)),
          'AB');
      // The same declared codespace over a composite font still means what it
      // says: its codes keep being read two bytes at a time.
      final composite = PdfDictionary()
        ..put(PdfName.type, PdfName.font)
        ..put(PdfName.subtype, PdfName('Type0'))
        ..put(PdfName.baseFont, PdfName('ABCDEF+Test'))
        ..put(PdfName.encoding, PdfName('Identity-H'))
        ..put(PdfName('ToUnicode'),
            _cmap('1 beginbfchar\n<0003> <0041>\nendbfchar'));
      expect(
          await _extract(
              'BT /F1 12 Tf <0003> Tj ET\n', _fontResources(composite)),
          'A');
    });

    test('a zero-padded code in the same block means the single-byte code',
        () async {
      // Exactly what the corpus writes: most codes one byte, the space two.
      final font = _simpleFont(
          toUnicode: _cmap('3 beginbfchar\n<41> <0041>\n<0020> <0020>\n'
              '<42> <0042>\nendbfchar'));
      expect(
          await _extract('BT /F1 12 Tf <412042> Tj ET\n', _fontResources(font)),
          'A B');
    });

    test('two spellings of one code that disagree leave it unmapped', () async {
      final font = _simpleFont(
          toUnicode: _cmap('2 beginbfchar\n<41> <0041>\n<0041> <0042>\n'
              'endbfchar'));
      expect(await _extract('BT /F1 12 Tf <41> Tj ET\n', _fontResources(font)),
          '�',
          reason: 'neither A nor B may be invented for an ambiguous entry');
    });

    test('codes the CMap omits fall back to the encoding the font declares',
        () async {
      // A producer that writes WinAnsi text and one en dash emits a ToUnicode
      // holding only the en dash; every other code is the encoding's to say.
      final font = _simpleFont(
          encoding: 'WinAnsiEncoding',
          flags: 32,
          toUnicode: _cmap('1 beginbfchar\n<96> <2013>\nendbfchar'));
      expect(
          await _extract('BT /F1 12 Tf <964143> Tj ET\n', _fontResources(font)),
          '–AC');
    });
  });

  group('fonts that declare an encoding and no ToUnicode', () {
    test('an embedded subset with a named base encoding still decodes',
        () async {
      expect(
          await _extract(
              'BT /F1 12 Tf <41E7> Tj ET\n',
              _fontResources(
                  _simpleFont(encoding: 'WinAnsiEncoding', flags: 32))),
          'Aç');
      // A symbolic font takes its encoding from the program's own cmap
      // (9.6.6.4), so the same name on one is not authoritative: it keeps
      // being refused instead of read through the Latin table.
      await expectLater(
          _extract(
              'BT /F1 12 Tf <41> Tj ET\n',
              _fontResources(
                  _simpleFont(encoding: 'WinAnsiEncoding', flags: 4))),
          throwsUnsupportedError);
    });
  });

  group('Identity subsets whose program carries no character map', () {
    test('glyphs the file never identifies become the replacement character',
        () async {
      final font = _identityFont(
          program: _sfntStub(const ['glyf', 'head', 'hhea', 'loca', 'maxp']));
      expect(
          await _extract(
              'BT /F1 12 Tf <00030004> Tj ET\n', _fontResources(font)),
          '��');
      // Only the Identity ordering leaves a CID meaningless. A registered
      // collection names tables that do assign characters to CIDs, and a font
      // using one is refused rather than declared unreadable.
      final japan = _identityFont(
          program: _sfntStub(const ['glyf', 'head', 'hhea', 'loca', 'maxp']),
          ordering: 'Japan1');
      await expectLater(
          _extract('BT /F1 12 Tf <0003> Tj ET\n', _fontResources(japan)),
          throwsUnsupportedError);
    });
  });

  test('BX and EX bracket a compatibility section and carry no text', () async {
    expect(
        await _extract(
            'BX EX BT /F1 12 Tf (Jornal) Tj ET BX EX\n',
            _fontResources(
                _simpleFont(encoding: 'WinAnsiEncoding', flags: 32))),
        'Jornal');
  });

  test('area redaction reads a page whose graphics state is transparency only',
      () async {
    final output = BytesBuilder(copy: false);
    final document = PdfDocument.create(PdfWriter.fromBytesBuilder(output));
    final page = await document.appendBlankPage();
    page.pdfRepresentation().put(
        PdfName.resources,
        PdfDictionary()
          ..put(
              PdfName.font,
              PdfDictionary()
                ..put(
                    PdfName('F1'),
                    PdfDictionary()
                      ..put(PdfName.type, PdfName.font)
                      ..put(PdfName.subtype, PdfName('Type1'))
                      ..put(PdfName.baseFont, PdfName('Helvetica'))
                      ..put(PdfName.encoding, PdfName('WinAnsiEncoding'))))
          ..put(
              PdfName('ExtGState'),
              PdfDictionary()
                ..put(
                    PdfName('GS0'),
                    PdfDictionary()
                      ..put(PdfName.type, PdfName('ExtGState'))
                      ..put(PdfName('ca'), PdfNumber(1)))));
    page.pdfRepresentation().put(
        PdfName.contents,
        PdfStream.withBytes(
            Uint8List.fromList(ascii.encode(
                '/GS0 gs\nBT /F1 12 Tf 72 700 Td (PUBLIC HEADING) Tj ET\n'
                'BT /F1 12 Tf 72 660 Td (SECRET ACCOUNT) Tj ET\n')),
            0));
    await document.close();

    final redacted = await PdfAreaRedaction.apply(output.takeBytes(), const [
      PdfRedactionArea(1, left: 60, bottom: 650, right: 400, top: 675)
    ]);
    final text = await _textOf(redacted);
    expect(text, contains('PUBLIC HEADING'));
    expect(text, isNot(contains('SECRET')));
  });
}
