import 'dart:convert';
import 'dart:io';

/// Regenerates `lib/src/io/resources/embedded_font_resources.dart` from the
/// checked-in resource files, so the runtime never touches the filesystem.
///
/// Run from the repository root:
///
/// ```
/// dart run tool/generate_font_resources.dart
/// ```
///
/// The Adobe Glyph List and the core-14 AFM metrics live under
/// `lib/src/io/resources/`, where their provenance and licence terms can be
/// audited; this tool only compresses and embeds them.
void main(List<String> arguments) {
  final root = Directory.current.path;
  final resources = '$root/lib/src/io/resources';

  final glyphList = File('$resources/AdobeGlyphList.txt').readAsBytesSync();
  final metrics = <String, List<int>>{};
  for (final name in _coreFonts) {
    final file = File('$resources/afm/$name.afm');
    if (!file.existsSync()) {
      stderr.writeln('missing metric file: ${file.path}');
      exitCode = 1;
      return;
    }
    metrics[name] = file.readAsBytesSync();
  }

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_font_resources.dart. '
        'Do not edit by hand.')
    ..writeln('// Embedded DATA retain their original terms; '
        'see resources/README.md.')
    ..writeln('// The generator and loading implementation are project code.')
    ..write(_notices)
    ..writeln("import 'dart:convert';")
    ..writeln("import '../../platform/compression.dart';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln('abstract final class EmbeddedFontResources {')
    ..writeln('  /// The 14 faces every conforming PDF reader supplies, and '
        'the only')
    ..writeln('  /// ones whose metrics this package can resolve without an '
        'embedded font.')
    ..writeln('  static const Set<String> standardFaces = {')
    ..writeln(_coreFonts.map((n) => "    '$n',").join('\n'))
    ..writeln('  };')
    ..writeln()
    ..writeln('  /// Reports an embedded AFM before a caller constructs a '
        'Type 1 program.')
    ..writeln('  /// Keeping this check separate avoids decoding the '
        'compressed metric data')
    ..writeln('  /// merely to decide whether a standard face is usable in '
        'this package.')
    ..writeln('  static bool hasMetrics(String name) => '
        '_metrics.containsKey(name);')
    ..writeln()
    ..writeln('  static String get glyphList =>')
    ..writeln('      utf8.decode(gzip.decode(base64.decode(_glyphList)));')
    ..writeln()
    ..writeln('  static Uint8List? metrics(String name) {')
    ..writeln('    final encoded = _metrics[name];')
    ..writeln('    if (encoded == null) return null;')
    ..writeln('    return Uint8List.fromList('
        'gzip.decode(base64.decode(encoded)));')
    ..writeln('  }')
    ..writeln()
    ..writeln('  static const Map<String, String> _metrics = {')
    ..writeln(_coreFonts.map((n) => "    '$n': ${_fieldName(n)},").join('\n'))
    ..writeln('  };')
    ..writeln()
    ..write(_literal('_glyphList', glyphList));
  for (final entry in metrics.entries) {
    buffer.write(_literal(_fieldName(entry.key), entry.value));
  }
  buffer.writeln('}');

  File('$resources/embedded_font_resources.dart')
      .writeAsStringSync(buffer.toString());
  stdout.writeln('embedded ${metrics.length} metric files');
}

const List<String> _coreFonts = [
  'Courier',
  'Courier-Bold',
  'Courier-Oblique',
  'Courier-BoldOblique',
  'Helvetica',
  'Helvetica-Bold',
  'Helvetica-Oblique',
  'Helvetica-BoldOblique',
  'Times-Roman',
  'Times-Bold',
  'Times-Italic',
  'Times-BoldItalic',
  'Symbol',
  'ZapfDingbats',
];

String _fieldName(String font) =>
    '_${font.replaceAll('-', '').replaceRange(0, 1, font[0].toLowerCase())}';

String _literal(String name, List<int> bytes) {
  final encoded = base64.encode(gzip.encode(bytes));
  final buffer = StringBuffer('  static const $name =\n');
  const chunk = 96;
  for (var i = 0; i < encoded.length; i += chunk) {
    final end = i + chunk < encoded.length ? i + chunk : encoded.length;
    buffer.writeln("      '${encoded.substring(i, end)}'");
  }
  buffer.writeln('      ;');
  return buffer.toString();
}

const String _notices = '''
// Adobe Glyph List data notices:
//  Copyright 2002-2019 Adobe (http://www.adobe.com/).
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are met:
//  Redistributions of source code must retain the above copyright notice, this
//  list of conditions and the following disclaimer. Redistributions in binary
//  form must reproduce the above copyright notice, this list of conditions and
//  the following disclaimer in the documentation and/or other materials
//  provided with the distribution. Neither the name of Adobe nor the names of
//  its contributors may be used to endorse or promote products derived from
//  this software without specific prior written permission.
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
//  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
//  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
//  CONSEQUENTIAL DAMAGES HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY.
//  dpdf retains its pre-existing duplicate entries and the aliases
//  Delta=0394, Omega=03A9, mu=03BC. These differ from upstream AGL.
//  Name: Adobe Glyph List; Table version: 2.0; Date: September 20, 2002.
//
// Core-14 metric data notices:
// Adobe Font Metrics (AFM) for PDF Core 14 Fonts
//
//    This file and the 14 PostScript(R) AFM files it accompanies may be used,
//    copied, and distributed for any purpose and without charge, with or
//    without modification, provided that all copyright notices are retained;
//    that the AFM files are not distributed without this file; that all
//    modifications to this file or any of the AFM files are prominently noted
//    in the modified file(s); and that this paragraph is not modified. Adobe
//    Systems has no responsibility or obligation to support the use of the AFM
//    files.
//
''';
