import 'dart:convert';
import 'dart:io';

/// Regenerates `lib/src/render/resources/standard_font_programs_vm.dart` from
/// the URW Core 35 files checked in under `assets/fonts/urw-core35/`.
///
/// Run from the repository root:
///
/// ```
/// dart run tool/generate_standard_fonts.dart
/// ```
///
/// The originals stay in `assets/` so their provenance and licence can be
/// audited; this tool only compresses and embeds them, the same way
/// `tool/generate_font_resources.dart` does with the Adobe Glyph List and the
/// core-14 metrics. Embedding is what makes the substitution work from an AOT
/// snapshot, where there is no package directory to read from.
void main(List<String> arguments) {
  final root = Directory.current.path;
  final source = '$root/assets/fonts/urw-core35';

  final programs = <String, List<int>>{};
  for (final name in _faces) {
    final file = File('$source/$name.otf');
    if (!file.existsSync()) {
      stderr.writeln('missing font file: ${file.path}');
      exitCode = 1;
      return;
    }
    programs[name] = file.readAsBytesSync();
  }

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_standard_fonts.dart. '
        'Do not edit by hand.')
    ..writeln('// The embedded font programs retain their own terms; '
        'see the notice below,')
    ..writeln('// assets/fonts/urw-core35/LICENSE.OFL and '
        'THIRD_PARTY_NOTICES.md.')
    ..write(_notice)
    ..writeln("import 'dart:convert';")
    ..writeln("import 'dart:typed_data';")
    ..writeln()
    ..writeln("import '../../platform/compression.dart';")
    ..writeln()
    ..writeln('/// The URW Core 35 programs that stand in for the fourteen '
        'standard PDF')
    ..writeln('/// fonts, compressed. Only reachable from the VM side of '
        '`standard_fonts.dart`:')
    ..writeln('/// a browser bundle must not carry a megabyte of typefaces '
        'nobody asked for.')
    ..writeln('abstract final class StandardFontPrograms {')
    ..writeln('  /// Inflates the program named [face], or null when there '
        'is no such face.')
    ..writeln('  ///')
    ..writeln('  /// The caller is expected to hold on to the result: '
        'inflating costs more')
    ..writeln('  /// than parsing it afterwards.')
    ..writeln('  static Uint8List? program(String face) {')
    ..writeln('    final encoded = _programs[face];')
    ..writeln('    if (encoded == null) return null;')
    ..writeln('    return Uint8List.fromList('
        'gzip.decode(base64.decode(encoded)));')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// Every face this carries.')
    ..writeln('  static Iterable<String> get faces => _programs.keys;')
    ..writeln()
    ..writeln('  static const Map<String, String> _programs = {')
    ..writeln(_faces.map((n) => "    '$n': ${_fieldName(n)},").join('\n'))
    ..writeln('  };')
    ..writeln();
  for (final entry in programs.entries) {
    buffer.write(_literal(_fieldName(entry.key), entry.value));
  }
  buffer.writeln('}');

  final target =
      File('$root/lib/src/render/resources/standard_font_programs_vm.dart');
  target.parent.createSync(recursive: true);
  target.writeAsStringSync(buffer.toString());
  stdout.writeln('embedded ${programs.length} font programs '
      '(${target.lengthSync() ~/ 1024} KiB of source)');
}

/// The URW faces that cover the fourteen standard PDF fonts.
///
/// Eleven of the thirty-five URW families are not here: a PDF that references
/// Palatino or Bookman without embedding it is not the case this solves, and
/// the bytes would be carried by everyone.
const List<String> _faces = [
  'NimbusSans-Regular',
  'NimbusSans-Bold',
  'NimbusSans-Oblique',
  'NimbusSans-BoldOblique',
  'NimbusRoman-Regular',
  'NimbusRoman-Bold',
  'NimbusRoman-Italic',
  'NimbusRoman-BoldItalic',
  'NimbusMonoPS-Regular',
  'NimbusMonoPS-Bold',
  'NimbusMonoPS-Italic',
  'NimbusMonoPS-BoldItalic',
  'StandardSymbolsPS',
  'D050000L',
];

String _fieldName(String face) {
  final name = face.replaceAll('-', '');
  return '_${name.replaceRange(0, 1, name[0].toLowerCase())}';
}

String _literal(String name, List<int> bytes) {
  final encoded = base64.encode(gzip.encode(bytes));
  final buffer = StringBuffer('  static const $name =\n');
  // Quarenta caracteres por linha, e nao noventa e seis: o verificador de
  // segredos do `pub publish` recusa o pacote quando uma linha traz `1/`
  // seguido de 43 ou mais caracteres de base64 — ele le isso como um refresh
  // token do Google OAuth. Em um megabyte de base64 aleatorio isso acontece,
  // e aconteceu. Com a linha curta o padrao nao cabe. O arquivo fica cerca de
  // 10% maior, barato perto de nao conseguir publicar.
  const chunk = 40;
  for (var i = 0; i < encoded.length; i += chunk) {
    final end = i + chunk < encoded.length ? i + chunk : encoded.length;
    buffer.writeln("      '${encoded.substring(i, end)}'");
  }
  buffer.writeln('      ;');
  return buffer.toString();
}

const String _notice = '''
// URW Core 35, Version 2.00, embedded unmodified except for compression.
//
//  Copyright (c) 2014,2015 by (URW)++ Design & Development
//
//  This Font Software is licensed under the SIL Open Font License, Version 1.1.
//  The full text travels with the package in
//  assets/fonts/urw-core35/LICENSE.OFL and is also at
//  http://scripts.sil.org/OFL
//
//  The copyright statement above declares no Reserved Font Name, so the family
//  names may be carried as they are. The font programs stay under the OFL;
//  they are not relicensed by being bundled with MIT code, and the OFL does
//  not reach the documents drawn with them.
//
''';
