import '../kernel/pdf/compression_constants.dart';

/// What the compressor is allowed to do to a document.
///
/// Every option here is **lossless for the rendered page**: the drawing
/// operators, fonts and images survive byte for byte unless an option says
/// otherwise in its own documentation. Options that drop information a reader
/// or an assistive technology uses are named for what they remove and default
/// to off.
class PdfCompressionOptions {
  /// Pack the objects that are not streams into object streams, and write a
  /// cross-reference stream instead of a table.
  ///
  /// This is where most of the structural saving comes from on a document with
  /// many small objects, and it costs nothing: the result is a PDF 1.5 file
  /// every reader since 2003 opens.
  final bool objectStreams;

  /// Deflate level for streams the compressor re-encodes, 0 to 9.
  final int compressionLevel;

  /// Re-deflate streams that are stored uncompressed, and re-deflate the ones
  /// whose existing Flate encoding is looser than [compressionLevel].
  ///
  /// Image streams whose filter is an image codec — `DCTDecode`, `JPXDecode`,
  /// `JBIG2Decode`, `CCITTFaxDecode` — are never touched: deflating an already
  /// compressed image makes it bigger.
  final bool recompressStreams;

  /// Replace objects with identical content by a single shared one.
  ///
  /// Documents assembled by merging, or generated by a tool that re-emits the
  /// same font or image on every page, often carry many duplicates.
  final bool deduplicateObjects;

  /// Drop objects nothing reachable from the catalog or the info dictionary
  /// refers to.
  ///
  /// Incremental updates leave superseded objects behind; so does deleting a
  /// page. Removing them is what makes a rewrite smaller than the original
  /// even before anything is recompressed.
  final bool removeOrphans;

  /// Remove the XMP metadata packet from the catalog and from every object
  /// that carries one.
  ///
  /// Off by default: the packet is where PDF/A and PDF/UA identification live,
  /// so removing it makes a conforming file stop conforming.
  final bool removeMetadata;

  /// Remove page thumbnail images, which no reader needs to render a page.
  final bool removeThumbnails;

  /// Remove `/PieceInfo`, the private data an authoring application keeps so
  /// it can round-trip its own documents.
  final bool removePieceInfo;

  /// Remove the logical structure tree and the `/MarkInfo` that announces it.
  ///
  /// Off by default, and it should usually stay off: this is the information a
  /// screen reader uses, and removing it makes the document fail PDF/UA and
  /// the accessible PDF/A levels.
  final bool removeStructureTree;

  /// Return the original bytes when the rewrite came out larger.
  ///
  /// A cross-reference stream and an object stream have a fixed cost, so on a
  /// document that is already small or already optimal the rewrite can grow
  /// the file. A compressor that hands back something bigger than it was given
  /// is not doing its job, so this defaults to on; turn it off only when you
  /// want the rewritten structure regardless of size.
  final bool neverGrow;

  const PdfCompressionOptions({
    this.objectStreams = true,
    this.compressionLevel = CraftCompressionConstants.bestCompression,
    this.recompressStreams = true,
    this.deduplicateObjects = true,
    this.removeOrphans = true,
    this.removeMetadata = false,
    this.removeThumbnails = true,
    this.removePieceInfo = true,
    this.removeStructureTree = false,
    this.neverGrow = true,
  });

  /// Only what cannot change how the document behaves in any reader.
  ///
  /// Keeps metadata, thumbnails and private application data, so a file that
  /// declares PDF/A or PDF/UA still declares it afterwards.
  static const PdfCompressionOptions conservative = PdfCompressionOptions(
    removeThumbnails: false,
    removePieceInfo: false,
  );

  /// Everything that keeps the pages identical, including dropping the
  /// structure tree.
  ///
  /// Use it for documents nobody will read with assistive technology and that
  /// make no archival claim.
  static const PdfCompressionOptions aggressive = PdfCompressionOptions(
    removeMetadata: true,
    removeStructureTree: true,
  );

  PdfCompressionOptions copyWith({
    bool? objectStreams,
    int? compressionLevel,
    bool? recompressStreams,
    bool? deduplicateObjects,
    bool? removeOrphans,
    bool? removeMetadata,
    bool? removeThumbnails,
    bool? removePieceInfo,
    bool? removeStructureTree,
    bool? neverGrow,
  }) {
    return PdfCompressionOptions(
      objectStreams: objectStreams ?? this.objectStreams,
      compressionLevel: compressionLevel ?? this.compressionLevel,
      recompressStreams: recompressStreams ?? this.recompressStreams,
      deduplicateObjects: deduplicateObjects ?? this.deduplicateObjects,
      removeOrphans: removeOrphans ?? this.removeOrphans,
      removeMetadata: removeMetadata ?? this.removeMetadata,
      removeThumbnails: removeThumbnails ?? this.removeThumbnails,
      removePieceInfo: removePieceInfo ?? this.removePieceInfo,
      removeStructureTree: removeStructureTree ?? this.removeStructureTree,
      neverGrow: neverGrow ?? this.neverGrow,
    );
  }
}

/// What the compressor did, and what it saved doing it.
class PdfCompressionReport {
  /// Size of the input in bytes.
  final int originalSize;

  /// Size of the output in bytes.
  final int compressedSize;

  /// Objects dropped because nothing referred to them.
  final int orphansRemoved;

  /// Objects replaced by an identical one that was already present.
  final int duplicatesMerged;

  /// Streams that were re-encoded.
  final int streamsRecompressed;

  /// Bytes saved by re-encoding streams, measured on the stream payloads
  /// alone, before the structural rewrite.
  final int streamBytesSaved;

  /// Entries removed by the `remove*` options, e.g. `Thumb` or `Metadata`.
  final Map<String, int> entriesRemoved;

  /// True when the rewrite came out larger and the original was returned
  /// unchanged, because [PdfCompressionOptions.neverGrow] was set.
  final bool keptOriginal;

  const PdfCompressionReport({
    required this.originalSize,
    required this.compressedSize,
    required this.orphansRemoved,
    required this.duplicatesMerged,
    required this.streamsRecompressed,
    required this.streamBytesSaved,
    required this.entriesRemoved,
    this.keptOriginal = false,
  });

  /// Bytes the output is smaller than the input. Negative when the rewrite
  /// grew the file, which happens on a document that was already optimal.
  int get bytesSaved => originalSize - compressedSize;

  /// Fraction of the original size that was saved, from 0 to 1.
  double get ratio => originalSize == 0 ? 0 : bytesSaved / originalSize;

  Map<String, Object?> toJson() => {
        'originalSize': originalSize,
        'compressedSize': compressedSize,
        'bytesSaved': bytesSaved,
        'ratio': ratio,
        'orphansRemoved': orphansRemoved,
        'duplicatesMerged': duplicatesMerged,
        'streamsRecompressed': streamsRecompressed,
        'streamBytesSaved': streamBytesSaved,
        'entriesRemoved': entriesRemoved,
        'keptOriginal': keptOriginal,
      };

  @override
  String toString() => keptOriginal
      ? 'PdfCompressionReport($originalSize bytes, kept: the rewrite was '
          'larger)'
      : 'PdfCompressionReport('
          '$originalSize -> $compressedSize bytes, '
          '${(ratio * 100).toStringAsFixed(1)}% smaller)';
}
